"""Flask entry point for local Python execution and single-worker Gunicorn."""

import atexit
import math
import mimetypes
import os
import sqlite3
from pathlib import Path

from flask import Flask, jsonify, render_template, request
from werkzeug.exceptions import HTTPException

from battery.service import BatteryService

ROOT = Path(__file__).resolve().parent
# Windows registry associations can otherwise serve .js as text/plain. With
# nosniff enabled browsers correctly refuse such scripts. Use explicit web types.
mimetypes.add_type("text/javascript", ".js")
mimetypes.add_type("text/css", ".css")


def validate_telemetry(payload):
    if not isinstance(payload, dict):
        raise ValueError("Expected a JSON object.")
    required = {"voltage", "current", "temperature", "device_load"}
    if not required <= payload.keys() or payload.keys() - required - {"source"}:
        raise ValueError("Supply voltage, current, temperature, device_load, and optionally source only.")
    if payload.get("source", "esp32") != "esp32":
        raise ValueError("POST source must be esp32; simulation is generated by the server.")
    bounds = {"voltage": (2.5, 4.3), "current": (0, 2), "temperature": (-20, 80), "device_load": (0, 1)}
    for key, (low, high) in bounds.items():
        value = payload[key]
        if type(value) not in (int, float) or not low <= value <= high or not math.isfinite(value):
            raise ValueError(f"{key} must be a finite number between {low} and {high}.")
    return {**payload, "source": "esp32"}


def validate_control(payload):
    allowed = {"simulation_enabled", "device_load", "reset"}
    if not isinstance(payload, dict) or not payload or payload.keys() - allowed:
        raise ValueError("Supply simulation_enabled, device_load, and/or reset.")
    for key in ("simulation_enabled", "reset"):
        if key in payload and type(payload[key]) is not bool:
            raise ValueError(f"{key} must be a JSON boolean.")
    if "device_load" in payload and payload["device_load"] not in ("LOW", "MEDIUM", "HIGH"):
        raise ValueError("device_load must be LOW, MEDIUM, or HIGH.")
    return payload


def create_app(config=None):
    application = Flask(__name__)

    def project_path(value):
        path = Path(value).expanduser()
        return path if path.is_absolute() else ROOT / path

    data_dir = project_path(os.environ.get("DATA_DIR", "data"))
    application.config.update(DATABASE_PATH=project_path(os.environ.get("DATABASE_PATH", str(data_dir / "battery.db"))),
                              MODEL_PATH=project_path(os.environ.get("MODEL_PATH", "models/runtime_model.pkl")),
                              START_WORKER=True, MAX_CONTENT_LENGTH=4096)
    application.config.update(config or {})
    service = BatteryService(application.config["DATABASE_PATH"], application.config["MODEL_PATH"])
    application.extensions["battery_service"] = service
    atexit.register(service.stop)

    @application.before_request
    def ensure_worker():
        if application.config["START_WORKER"]:
            service.start()

    @application.after_request
    def response_headers(response):
        if request.path.startswith("/api/") or request.path == "/health":
            response.headers["Cache-Control"] = "no-store"
        response.headers["X-Content-Type-Options"] = "nosniff"
        return response

    @application.errorhandler(ValueError)
    def invalid_input(error):
        return jsonify(status="error", error=str(error)), 400

    @application.errorhandler(HTTPException)
    def http_error(error):
        if request.path.startswith("/api/"):
            return jsonify(status="error", error=error.description), error.code
        return error

    @application.errorhandler(sqlite3.Error)
    def database_error(error):
        application.logger.error("Database operation failed: %s", error)
        return jsonify(status="error", error="Local database unavailable; check the server log."), 503

    @application.route("/")
    def index():
        return render_template("index.html")

    @application.get("/health")
    def health():
        model_status = "loaded" if service.predictor.model is not None else "fallback"
        try:
            with service.db.connection() as connection:
                connection.execute("SELECT id FROM telemetry LIMIT 1").fetchone()
        except sqlite3.Error:
            return jsonify(status="unhealthy", model=model_status, database="unavailable"), 503
        # A missing model retains the existing calculated fallback functionality.
        return jsonify(status="healthy" if model_status == "loaded" else "degraded",
                       model=model_status, database="connected")

    @application.get("/api/telemetry")
    def telemetry():
        limit = request.args.get("limit", "60")
        if not limit.isascii() or not limit.isdigit() or len(limit) > 2 or not 1 <= int(limit) <= 60:
            raise ValueError("limit must be an integer between 1 and 60.")
        return jsonify(service.snapshot(int(limit)))

    @application.post("/api/telemetry")
    def receive_telemetry():
        reading = service.receive(validate_telemetry(request.get_json()))
        return jsonify(status="success", **reading), 201

    @application.post("/api/control")
    def control():
        return jsonify(service.control(validate_control(request.get_json())))

    return application


# Gunicorn imports this WSGI object. The background thread starts in its worker,
# not the master process; see gunicorn.conf.py. Test factories remain available.
app = create_app()


if __name__ == "__main__":
    app.extensions["battery_service"].start()
    try:
        app.run(host=os.environ.get("FLASK_HOST", "127.0.0.1"),
                port=int(os.environ.get("PORT", "5000")), debug=False, use_reloader=False)
    finally:
        app.extensions["battery_service"].stop()
